---
- hosts: ubuntu

  tasks:

  - name: install/update essential software for Ubuntu
    apt: pkg={{item}} state=latest

    with_items:

    - nmap
    - wget
    - vim
    - open-vm-tools

- hosts: centos
  remote_user: root
  tasks:

  - name: install/update essential software for CentOS
    yum: name={{item}} state=latest

    with_items:

    - nmap
    - wget
    - vim
    - open-vm-tools
    - yum
