---
- hosts: all #teeb selle kõikidele hostidel

  tasks: #taskid, mida järgida

  #Need taskid on Ubuntule
  - name: Ensure/Import ansible key #Vaatab kas ansible key on juba olemas, kui mitte siis impordib
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12")
    apt_key: id=7BB9C367 url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x7BB9C367" state=present

  - name: Add RIA key
    apt_key: url=http://apt.tt.kit/apt.pub.key state=present #lisab ria repo public key
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12")

  - name: Determine Linux distribution codename
    command: lsb_release -cs #vaatab linuxi realease nime
    register: release_codename #registreerib selle

#  - name: Check for RIA repo source.list
#    stat: path=/etc/apt/apt.tt.kit.list #vaatab kas fail on seal juba olemas
#    register: file_exists #registreerib selle

  - name: Download ria source #laeb ria sources listi alla linux release codename abiga
    get_url: url=http://apt.tt.kit/ubuntu/sources/{{release_codename.stdout}}/apt.tt.kit.list dest=/etc/apt/ #laeb selle asukohta /apt/
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12")

  - name: Move RIA repo to source file
    command: cp /etc/apt/apt.tt.kit.list /etc/apt/sources.list #kopeerib faili source.list'i
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12")

  - name: Add Ansible REPO to the LIST #lisab ansible repo sources listi
    apt_repository: repo='ppa:ansible/ansible' state=present
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12")
    
#  - name: remove specifig signing key #eemaldab signing key
#    apt_key: id=0x7BB9C367 state=absent #state=absent eemaldab

#  - name: remove ANSIBLE repo #eemaldab ansible repo
#    apt_repository: repo='ppa:ansible/ansible' state=absent

  #Need taskid on CentOS'ile
  #Only if this is a CentOS (NOT TESTED!)
  - name: Configure YUM repository
    action: get_url url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo 
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

  - name: Import repository key
    action: shell rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

  - name: Configure YUM repository
    action: yum name=jenkins state=present
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

  - name: Update Repo list #uuendab repo listi
    apt: update_cache=yes cache_valid_time=86400
    notify: apt update
