---

- name: Generate passwords #Genereerib parooli
  shell: python -c 'import crypt; print crypt.crypt("{{ upassword }}", "\$6\$SALTsalt\$")'
  register: genpass

- name: Creating user "{{ uusername }}" with admin access #teeb uue kasutaja admin õigustega
  user: name={{ uusername }} password={{ upassword |password_hash('sha512') }} shell=/bin/bash append=yes #annab kasutajale parooli, shelli ja grupi
  when:  assigned_role  == "yes"

- name: Creating users "{{ uusername }}" without admin access #teeb uue kasutaja mitte-admin õigustega
  user: name={{ uusername }} password={{ genpass.stdout }} shell=/bin/bash #annab kasutajale parooli ja shelli
  when:  assigned_role == "no"

- name: Expiring password for user "{{ uusername }}" #Parooli kehtivus
  shell: chage -d 0 "{{ uusername }}" #Annab kasutajale m2rku et peab parooli vahetama, et kehtivusaeg l6ppes
