---

- name: Generate passwords
  shell: python -c 'import crypt; print crypt.crypt("{{ upassword }}", "\$6\$SALTsalt\$")'
  register: genpass

- name: Creating user "{{ uusername }}" with admin access
  user: name={{ uusername }} password={{ upassword |password_hash('sha512') }} shell=/bin/bash groups=root append=yes
  when:  assigned_role  == "yes"

- name: Creating users "{{ uusername }}" without admin access
  user: name={{ uusername }} password={{ genpass.stdout }} shell=/bin/bash
  when:  assigned_role == "no"

- name: Expiring password for user "{{ uusername }}"
  shell: chage -d 0 "{{ uusername }}"
