---
- hosts: centos
  remote_user: root
  tasks:

#https://www.zigg.com/2013/yum-repository-bootstrapping-ansible.html
  - name: bootstrap epel-release install for CentOS
    copy: src=ansible-bootstrap-epel.repo
          dest=/etc/yum.repos.d/
          owner=root group=root mode=0644

  - name: epel-release install for CentOS
    yum: name=epel-release
         enablerepo=ansible-bootstrap-epel
         state=present

  - name: epel repository enable CentOS
    ini_file: dest=/etc/yum.repos.d/epel.repo
              section=epel
              option=enabled
              value=1

  - name: Install Zabbix Repository Key CentOS 
    rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

#http://jurgenvm.blogspot.com.ee/2014/12/configure-zabbix-server-on-centos-66.html
  - name: Install Zabbix Repository and other packages needed by Ansible for CentOS
    yum: pkg={{item}} state=installed  
    with_items:
      - policycoreutils-python
      - libselinux-python
      - http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm

  - name: Install Zabbix packages for CentOS
    yum: pkg={{item}} state=installed
    with_items:
      - zabbix-agent

  - name: Copy zabbix conf for CentOS
    copy: src=./files-centos-7/zabbix_agentd.conf
          dest=/etc/zabbix/zabbix_agentd.conf
          owner=root group=root mode=0644

  handlers:
  - name: Start Zabbix-agent
    service: name=zabbix-agent state=started enabled=yes

  - name: Opening port 10050
    firewalld: port=10050/tcp permanent=true state=enabled

#Taskid ubuntule!!
- hosts: ubuntu
  tasks:

  - name: Install Zabbix packages for Ubuntu
    apt: pkg={{item}} state=installed
    with_items:
      - zabbix-agent

  - name: Copy zabbix conf for Ubuntu
    copy: src=./files-ubuntu-14/zabbix_agentd.conf
          dest=/etc/zabbix/zabbix_agentd.conf
          owner=root group=root mode=0644

  handlers:
  - name: Start Zabbix-agent
    service: name=zabbix-agent state=started enabled=yes

  - name: Opening port 10050
    firewalld: port=10050/tcp permanent=true state=enabled
