---
- hosts: all
  sudo: true
  tasks:

  - name: updates a server
    apt: update_cache=yes
    notify: apt update
  
  - name: upgrades a server
    apt: upgrade=full

  - name: dist upgrades a server
    apt: upgrade=dist
