---
- hosts: '{{ host }}'
  remote_user: '{{ user }}'

  tasks:
  - name: Add RSA key to the remote host
    authorized_key: user='{{ user }}' key="{{ lookup('file', '/home/kanakas/.ssh/id_rsa.pub') }}"
